.MODEL SMALL
.STACK 100H

.DATA
    NUM DB ?
    MSG DB 0DH,0AH, 'ENTER A NUMBER$'
    MSG_EVEN DB 0DH,0AH, 'NUMBER IS EVEN$'
    MSG_ODD DB 0DH,0AH, 'NUMBER IS ODD$'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ;PROMT TO ENTER A NUMBER
    MOV AH, 09H
    LEA DX, MSG
    INT 21H
    
    ;INPUT A NUMBER FROM USER
    MOV AH,1
    INT 21H
    SUB AL, 30H
    MOV NUM, AL
                          
    ;CHECK ODD/EVEN
    MOV AL,NUM
    TEST AL, 1
    JZ EVEN_NUMBER
    
ODD_NUMBER:
    MOV DX, OFFSET MSG_ODD
    MOV AH, 9
    INT 21H
    JMP EXIT

EVEN_NUMBER:
    MOV DX, OFFSET MSG_EVEN
    MOV AH, 9
    INT 21H
    
EXIT:
    MOV AH, 4CH
    INT 21H
   
MAIN ENDP
END MAIN