.MODEL SMALL
.STACK 100H

.DATA      ;CAN DECLARE VAR

A DB 7     ;VAR_NAME SIZE(B=BYTE,W=WORD) VALUE



.CODE



MAIN PROC ; MAIN PROGRAM START

     ;INITIALIZE DS
     MOV AX,@DATA         ;SEGMENT ASSIGNE IN AX
     MOV DS,AX            ;SEGMENT NUMBER MOVE TO DS
                          
     MOV DL,A             ;DL=7 BUT ITS STORED IN DL AS ASCII
     ADD DL,30H           ;ADDING 30 WILL GIVE THE ASCII OF THAT A'S ASCII AND PRINT THE SIMILLAR DECIMAL
     MOV AH,2
     INT 21H
   
MAIN ENDP 
     END MAIN